typography_spectrum: 0.9609001337084919
color:
  brandStrength: 0.042133408365771174
  lightness: 0.8595470997970551
  saturation: 0.5691161844879389
  rhythmicContrast: 0.23668632842600346
  brandColors:
    - '#D7FBF7'
    - '#440B74'
    - '#BFC8C7'
    - '#6F7978'
    - '#BF693A'
github: true
layout_spectrum: 0.5974512954708189
author:
  name: infiniti99
  email: infiniti1986@gmail.com
  url: 'https://thegrid.ai/infiniti-creative-landscape-design/'
name: Infiniti Creative Landscape Design
title: About us
content: []
description: >-
  One thing remains constant and that is our drive and determination to do our
  best each day.We are a design build landscape company and I believe no matter
  how much work you have done or how good your work is or is not,Your only as
  good as your last job and each job is a audition for your next.So each job for
  us, big or small is given the same attention to detail and energy that we are
  known for on a daily basis.
